export const APP = {
    SETTING_DATA: 'SETTING_DATA',
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
    SET_HEADER_TEXT: 'SET_HEADER_TEXT',
}

export const SETTING = {
    SETTING_DATA: "SETTING_DATA",
    SET_COLOR: "SET_COLOR"
}

export const USER = {
    USER_DATA: 'USER_DATA',
    USER_AVATAR: 'USER_AVATAR'
}

export const PRODUCT = {
    PRODUCT_DATA: 'PRODUCT_DATA',
}

export const CLASS = {
    SET_DATA_CLASS: 'SET_DATA_CLASS',
    SET_DATA_CLASS_DETAIL: 'SET_DATA_CLASS_DETAIL',
    USER_AVATAR: 'USER_AVATAR'
}