module.exports = {
    KEY_DRAWER: 'KEY_DRAWER',
    KEY_CURRENT_SCENE: 'KEY_CURRENT_SCENE',
    KEY_API_STRINGS: 'KEY_API_STRINGS',

    AUTH_TOKEN: 'KEY_AUTH_TOKEN',
    ACCOUNT_ID: 'KEY_ACCOUNT_ID',
    ASSIGNED_PERMISSION: 'ASSIGNED_PERMISSION',

    //ASYNC_STORAGE_KEY
    KEY_ASYNC_STORAGE: 'HONEY_REPORT_STORAGE:',
    KEY_ASYNC_STORAGE_SETTINGS: 'KEY_ASYNC_STORAGE_SETTINGS',
    KEY_ASYNC_STORAGE_USER: 'KEY_ASYNC_STORAGE_USER',
    KEY_ASYNC_STORAGE_PRODUCT: 'KEY_ASYNC_STORAGE_PRODUCT',

};